import{audit,authorize,getDB,scopeFilter}from'../../../lib/auth-server';
export const runtime='nodejs';export const dynamic='force-dynamic';
const mapOccurrence=(r:any)=>({id:r.id,createdAt:r.created_at,date:r.date||'',time:r.time||'',company:r.company_id||'',companyName:r.company_name||'',unit:r.unit_id||'',unitName:r.unit_name||'',operation:r.operation||'',location:r.location||'',city:r.city||'',uf:r.uf||'',nature:r.nature||'',type:r.type||'',potential:r.potential||'',victim:r.victim?'Sim':'Não',materialDamage:r.material_damage?'Sim':'Não',environmentalImpact:r.environmental_impact?'Sim':'Não',description:r.description||'',driver:r.driver||'',document:r.document||'',plate:r.plate||'',fleet:r.fleet||'',trailer:r.trailer||'',trailerPlate:r.trailer_plate||'',birdSuggested:r.bird_suggested||'',birdReason:r.bird_reason||'',birdValidated:r.bird_validated||'',status:r.status||'Registrado'});
export async function GET(req:Request){const a=await authorize(req);if(a.response)return a.response;const db=getDB(),url=new URL(req.url),id=url.searchParams.get('id'),s=scopeFilter(a.user!,'o');if(id){const row=await db.prepare("SELECT o.*,c.name company_name,u.name unit_name FROM occurrences o LEFT JOIN companies c ON c.id=o.company_id LEFT JOIN units u ON u.id=o.unit_id WHERE o.id=?"+s.sql).bind(id,...s.values).first();if(!row)return Response.json({error:'not_found'},{status:404});const third=await db.prepare("SELECT * FROM third_parties WHERE occurrence_id=? ORDER BY rowid LIMIT 1").bind(id).first();return Response.json({...mapOccurrence(row),thirdParty:!!third,thirdPartyType:third?.type||'',thirdPartyName:third?.name||'',contactName:third?.contact_name||'',phone1:third?.phone1||'',phone2:third?.phone2||'',email:third?.email||'',thirdNotes:third?.notes||''})}const rows=await db.prepare("SELECT o.*,c.name company_name,u.name unit_name FROM occurrences o LEFT JOIN companies c ON c.id=o.company_id LEFT JOIN units u ON u.id=o.unit_id WHERE 1=1"+s.sql+" ORDER BY o.created_at DESC").bind(...s.values).all();return Response.json(rows.results.map(mapOccurrence))}
export async function POST(req:Request){
  const a=await authorize(req,['ADMIN','SSMA','GESTOR']);if(a.response)return a.response;
  const db=getDB(),o:any=await req.json(),u=a.user!;
  if(!o.id||!o.company||!o.unit||!o.date||!o.nature)return Response.json({error:'required_fields',detail:'Preencha Data, Empresa, Unidade e Natureza.'},{status:400});
  if(u.role!=='ADMIN'&&u.companyId&&o.company!==u.companyId)return Response.json({error:'outside_scope',detail:'Empresa fora do escopo do usuário.'},{status:403});
  if(u.role!=='ADMIN'&&u.unitId&&o.unit!==u.unitId)return Response.json({error:'outside_scope',detail:'Unidade fora do escopo do usuário.'},{status:403});
  try{
    try{await db.prepare("ALTER TABLE occurrences ADD COLUMN created_by TEXT").run()}catch{}
    await db.prepare(`INSERT INTO occurrences(id,company_id,unit_id,date,time,operation,location,city,uf,nature,type,potential,victim,material_damage,environmental_impact,description,driver,document,plate,fleet,trailer,trailer_plate,bird_suggested,bird_reason,bird_validated,status,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(o.id,o.company||null,o.unit||null,o.date||null,o.time||null,o.operation||null,o.location||null,o.city||null,o.uf||null,o.nature||null,o.type||null,o.potential||null,o.victim==='Sim'?1:0,o.materialDamage==='Sim'?1:0,o.environmentalImpact==='Sim'?1:0,o.description||null,o.driver||null,o.document||null,o.plate||null,o.fleet||null,o.trailer||null,o.trailerPlate||null,o.birdSuggested||null,o.birdReason||null,o.birdValidated||null,o.status||'Registrado',u.id,o.createdAt||new Date().toISOString(),new Date().toISOString()).run();
    if(o.thirdParty&&o.thirdPartyName)await db.prepare("INSERT INTO third_parties(id,occurrence_id,type,name,contact_name,phone1,phone2,email,notes) VALUES(?,?,?,?,?,?,?,?,?)").bind('THR-'+crypto.randomUUID(),o.id,o.thirdPartyType||null,o.thirdPartyName,o.contactName||null,o.phone1||null,o.phone2||null,o.email||null,o.thirdNotes||null).run();
    await audit(db,u.id,'Ocorrência registrada','Registro criado no SENTINEL',o.id);
    return Response.json({ok:true,id:o.id},{status:201});
  }catch(e:any){
    return Response.json({error:'occurrence_create_failed',detail:String(e?.message||e||'Erro desconhecido')},{status:500});
  }
}
export async function PATCH(req:Request){const a=await authorize(req,['ADMIN','SSMA','GESTOR']);if(a.response)return a.response;const db=getDB(),p:any=await req.json(),s=scopeFilter(a.user!,'occurrences');if(!p.id)return Response.json({error:'id_required'},{status:400});const allowed=await db.prepare("SELECT id FROM occurrences WHERE id=?"+s.sql.replaceAll('occurrences.','')).bind(p.id,...s.values).first();if(!allowed)return Response.json({error:'not_found'},{status:404});if(p.birdValidated!==undefined)await db.prepare("UPDATE occurrences SET bird_validated=?,status=COALESCE(?,status),updated_at=? WHERE id=?").bind(p.birdValidated,p.status||null,new Date().toISOString(),p.id).run();else if(p.status!==undefined)await db.prepare("UPDATE occurrences SET status=?,updated_at=? WHERE id=?").bind(p.status,new Date().toISOString(),p.id).run();await audit(db,a.user!.id,'Ocorrência atualizada','Status/classificação atualizados',p.id);return Response.json({ok:true})}
export async function DELETE(req:Request){const a=await authorize(req,['ADMIN']);if(a.response)return a.response;const db=getDB(),id=new URL(req.url).searchParams.get('id');if(!id)return Response.json({error:'id_required'},{status:400});const found=await db.prepare("SELECT id FROM occurrences WHERE id=?").bind(id).first();if(!found)return Response.json({error:'not_found'},{status:404});await audit(db,a.user!.id,'Ocorrência excluída','Exclusão administrativa da ocorrência '+id,id);await db.batch([db.prepare("DELETE FROM attachments WHERE occurrence_id=?").bind(id),db.prepare("DELETE FROM closures WHERE occurrence_id=?").bind(id),db.prepare("DELETE FROM actions WHERE occurrence_id=?").bind(id),db.prepare("DELETE FROM investigations WHERE occurrence_id=?").bind(id),db.prepare("DELETE FROM third_parties WHERE occurrence_id=?").bind(id),db.prepare("DELETE FROM occurrences WHERE id=?").bind(id)]);return Response.json({ok:true})}