export type Occurrence={id:string;createdAt:string;date:string;time:string;company:string;companyName?:string;unit:string;unitName?:string;operation:string;location:string;city:string;uf:string;nature:string;type:string;potential:string;victim:string;materialDamage:string;environmentalImpact:string;description:string;driver:string;document:string;plate:string;fleet:string;trailer:string;trailerPlate:string;thirdParty:boolean;thirdPartyType?:string;thirdPartyName?:string;contactName?:string;phone1?:string;phone2?:string;email?:string;thirdNotes?:string;birdSuggested:string;birdReason:string;birdValidated?:string;status:string};
export async function listOccurrences():Promise<Occurrence[]>{const r=await fetch("/api/occurrences",{cache:"no-store"});if(!r.ok)throw new Error("Falha ao consultar ocorrências");return r.json()}
export async function saveOccurrence(o:Occurrence){const r=await fetch("/api/occurrences",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(o)});let x:any={};try{x=await r.json()}catch{}if(!r.ok)throw new Error(x?.detail||x?.error||"Falha ao registrar ocorrência");return x}
export async function getOccurrence(id:string):Promise<Occurrence|undefined>{const r=await fetch("/api/occurrences?id="+encodeURIComponent(id),{cache:"no-store"});if(r.status===404)return; if(!r.ok)throw new Error("Falha ao consultar ocorrência");return r.json()}
export async function updateOccurrence(id:string,patch:Partial<Occurrence>){const r=await fetch("/api/occurrences",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,...patch})});if(!r.ok)throw new Error("Falha ao atualizar ocorrência");return r.json()}
export type Investigation={occurrenceId:string;validatedBird:string;reclassReason:string;immediateCause:string;contributingFactors:string[];rootCause:string;method:string;why1:string;why2:string;why3:string;why4:string;why5:string;conclusion:string;updatedAt:string};
export async function getInvestigation(id:string):Promise<Investigation|undefined>{const r=await fetch("/api/investigations?occurrenceId="+encodeURIComponent(id),{cache:"no-store"});if(!r.ok)return;const x=await r.json();return x||undefined}
export async function saveInvestigation(i:Investigation){const r=await fetch("/api/investigations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(i)});let x:any={};try{x=await r.json()}catch{}if(!r.ok)throw new Error(x?.detail||x?.error||"Falha ao salvar investigação");return x}
export function classifyBird(x:Partial<Occurrence>){if((x as any).death==='Sim')return {level:'Acidente fatal',reason:'Ocorrência com óbito registrado.'};if(x.victim==='Sim')return {level:'Lesão',reason:'Ocorrência com vítima registrada.'};if(x.materialDamage==='Sim'||x.environmentalImpact==='Sim')return {level:'Acidente',reason:'Ocorrência com consequência material ou ambiental registrada.'};if(x.nature==='Quase acidente')return {level:'Quase acidente',reason:'Evento sem consequência registrada, classificado como quase acidente.'};return {level:'Pendente de validação',reason:'Informações atuais não permitem classificação automática conclusiva.'}}
export type ActionItem={id:string;occurrenceId:string;description:string;type:string;origin:string;responsible:string;deadline:string;priority:string;status:string;evidence:string;validation:string;effectiveness:string;effectivenessNote:string;createdAt:string;completedAt?:string};
export async function listActions(occurrenceId?:string):Promise<ActionItem[]>{const q=occurrenceId?"?occurrenceId="+encodeURIComponent(occurrenceId):"";const r=await fetch("/api/actions"+q,{cache:"no-store"});if(!r.ok)throw new Error("Falha ao consultar ações");return r.json()}
export async function saveAction(a:ActionItem){const r=await fetch("/api/actions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(a)});let x:any={};try{x=await r.json()}catch{}if(!r.ok)throw new Error(x?.detail||x?.error||"Falha ao salvar ação");return x}
export async function updateAction(id:string,patch:Partial<ActionItem>){const r=await fetch("/api/actions",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,...patch})});let x:any={};try{x=await r.json()}catch{}if(!r.ok)throw new Error(x?.detail||x?.error||"Falha ao atualizar ação");return x}
export function actionState(a:ActionItem){if(a.status==='Concluída')return 'Concluída';if(a.deadline&&new Date(a.deadline+'T23:59:59')<new Date())return 'Vencida';return a.status}
export type Closure={occurrenceId:string;conclusion:string;lessons:string;recommendations:string;responsible:string;closedAt:string};
export async function closureCheck(id:string):Promise<string[]>{const r=await fetch("/api/closures?occurrenceId="+encodeURIComponent(id),{cache:"no-store"});if(!r.ok)return["Falha ao validar encerramento"];const x=await r.json();return x.pending||[]}
export async function closeOccurrence(c:Closure):Promise<string[]>{const r=await fetch("/api/closures",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(c)});let x:any={};try{x=await r.json()}catch{}if(r.status===409)return x.pending||[];if(!r.ok)throw new Error(x?.detail||x?.error||"Falha ao encerrar ocorrência");return[]}
export async function dashboardStats(){const [os,as]=await Promise.all([listOccurrences(),listActions()]);return{total:os.length,accidents:os.filter(x=>x.nature==='Acidente').length,nearMisses:os.filter(x=>x.nature==='Quase acidente').length,fatal:os.filter(x=>(x.birdValidated||x.birdSuggested)==='Acidente fatal').length,overdueActions:as.filter(x=>actionState(x)==='Vencida').length,openActions:as.filter(x=>actionState(x)!=='Concluída').length,closed:os.filter(x=>x.status==='Encerrado').length,investigation:os.filter(x=>x.status==='Em investigação').length,plan:os.filter(x=>x.status==='Plano de ação').length}}
