export type Occurrence={id:string;createdAt:string;date:string;time:string;company:string;unit:string;operation:string;location:string;city:string;uf:string;nature:string;type:string;potential:string;victim:string;materialDamage:string;environmentalImpact:string;description:string;driver:string;document:string;plate:string;fleet:string;trailer:string;trailerPlate:string;thirdParty:boolean;thirdPartyType?:string;thirdPartyName?:string;contactName?:string;phone1?:string;phone2?:string;email?:string;thirdNotes?:string;birdSuggested:string;birdReason:string;birdValidated?:string;status:string};
const KEY='sentinel_occurrences_v1';
export function listOccurrences():Occurrence[]{if(typeof window==='undefined')return[];try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}
export function saveOccurrence(o:Occurrence){const all=listOccurrences();localStorage.setItem(KEY,JSON.stringify([o,...all]));}
export function getOccurrence(id:string){return listOccurrences().find(x=>x.id===id)}
export function updateOccurrence(id:string,patch:Partial<Occurrence>){const all=listOccurrences();const next=all.map(x=>x.id===id?{...x,...patch}:x);localStorage.setItem(KEY,JSON.stringify(next));return next.find(x=>x.id===id)}
export type Investigation={occurrenceId:string;validatedBird:string;reclassReason:string;immediateCause:string;contributingFactors:string[];rootCause:string;method:string;why1:string;why2:string;why3:string;why4:string;why5:string;conclusion:string;updatedAt:string};
const IKEY='sentinel_investigations_v1';
export function getInvestigation(id:string):Investigation|undefined{if(typeof window==='undefined')return;try{return JSON.parse(localStorage.getItem(IKEY)||'[]').find((x:Investigation)=>x.occurrenceId===id)}catch{return}}
export function saveInvestigation(i:Investigation){let all:Investigation[]=[];try{all=JSON.parse(localStorage.getItem(IKEY)||'[]')}catch{};all=[i,...all.filter(x=>x.occurrenceId!==i.occurrenceId)];localStorage.setItem(IKEY,JSON.stringify(all));updateOccurrence(i.occurrenceId,{birdValidated:i.validatedBird,status:'Em investigação'});}
export function classifyBird(x:Partial<Occurrence>){if(x.victim==='Sim'&&x.potential==='Fatal')return {level:'Acidente fatal',reason:'Vítima registrada com potencial de gravidade fatal.'};if(x.victim==='Sim')return {level:'Lesão',reason:'Ocorrência com vítima registrada.'};if(x.materialDamage==='Sim'||x.environmentalImpact==='Sim')return {level:'Acidente',reason:'Ocorrência com consequência material ou ambiental registrada.'};if(x.nature==='Quase acidente')return {level:'Quase acidente',reason:'Evento sem consequência registrada, classificado como quase acidente.'};return {level:'Pendente de validação',reason:'Informações atuais não permitem classificação automática conclusiva.'}}
export type ActionItem={id:string;occurrenceId:string;description:string;type:string;origin:string;responsible:string;deadline:string;priority:string;status:string;evidence:string;validation:string;effectiveness:string;effectivenessNote:string;createdAt:string;completedAt?:string};
const AKEY='sentinel_actions_v1';
export function listActions(occurrenceId?:string):ActionItem[]{if(typeof window==='undefined')return[];try{const a=JSON.parse(localStorage.getItem(AKEY)||'[]');return occurrenceId?a.filter((x:ActionItem)=>x.occurrenceId===occurrenceId):a}catch{return[]}}
export function saveAction(a:ActionItem){const all=listActions();localStorage.setItem(AKEY,JSON.stringify([a,...all]));updateOccurrence(a.occurrenceId,{status:'Plano de ação'})}
export function updateAction(id:string,patch:Partial<ActionItem>){const all=listActions();localStorage.setItem(AKEY,JSON.stringify(all.map(x=>x.id===id?{...x,...patch}:x)))}
export function actionState(a:ActionItem){if(a.status==='Concluída')return 'Concluída';if(a.deadline&&new Date(a.deadline+'T23:59:59')<new Date())return 'Vencida';return a.status}

export type Closure={occurrenceId:string;conclusion:string;lessons:string;recommendations:string;responsible:string;closedAt:string};
const CKEY='sentinel_closures_v1';
export function closureCheck(id:string){const o=getOccurrence(id);const inv=getInvestigation(id);const acts=listActions(id);const open=acts.filter(a=>actionState(a)!=='Concluída');const pending:string[]=[];if(!o?.birdValidated)pending.push('Classificação Bird não validada');if(!inv?.rootCause)pending.push('Causa raiz não definida');if(!inv?.conclusion)pending.push('Investigação sem conclusão');if(acts.length===0)pending.push('Plano de ação não cadastrado');if(open.length)pending.push(open.length+' ação(ões) ainda aberta(s)');return pending}
export function closeOccurrence(c:Closure){const pending=closureCheck(c.occurrenceId);if(pending.length)return pending;let all:Closure[]=[];try{all=JSON.parse(localStorage.getItem(CKEY)||'[]')}catch{};localStorage.setItem(CKEY,JSON.stringify([c,...all.filter(x=>x.occurrenceId!==c.occurrenceId)]));updateOccurrence(c.occurrenceId,{status:'Encerrado'});return[]}
export function dashboardStats(){const os=listOccurrences(),as=listActions();return{total:os.length,accidents:os.filter(x=>x.nature==='Acidente').length,near:os.filter(x=>x.nature==='Quase acidente').length,fatal:os.filter(x=>(x.birdValidated||x.birdSuggested)==='Acidente fatal').length,overdue:as.filter(x=>actionState(x)==='Vencida').length,openActions:as.filter(x=>actionState(x)!=='Concluída').length,closed:os.filter(x=>x.status==='Encerrado').length,investigation:os.filter(x=>x.status==='Em investigação').length,plan:os.filter(x=>x.status==='Plano de ação').length}}