'use client';
import{useEffect,useState}from'react';import Link from'next/link';import{Building2,MapPin,Trash2,UserPlus,Users}from'lucide-react';
type Company={id:string;name:string};type Unit={id:string;company_id:string;name:string};
export default function Page(){const[companies,setCompanies]=useState<Company[]>([]),[units,setUnits]=useState<Unit[]>([]),[users,setUsers]=useState<any[]>([]),[unitCompany,setUnitCompany]=useState(''),[userCompany,setUserCompany]=useState(''),[msg,setMsg]=useState('');
async function load(){const[c,u]=await Promise.all([fetch('/api/cadastros',{cache:'no-store'}),fetch('/api/usuarios',{cache:'no-store'})]);if(!c.ok||!u.ok)throw new Error('Falha ao carregar administração');const cm=await c.json(),us=await u.json();setCompanies(cm.companies||[]);setUnits(cm.units||[]);setUsers(Array.isArray(us)?us:[])}
useEffect(()=>{load().catch(()=>setMsg('Não foi possível carregar os dados administrativos.'))},[]);
async function addCompany(e:any){e.preventDefault();const f=e.currentTarget,d=new FormData(f);const r=await fetch('/api/cadastros',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:'company',name:d.get('name')})});if(r.ok){f.reset();setMsg('Empresa cadastrada com sucesso.');await load()}else setMsg('Não foi possível cadastrar a empresa.')}
async function addUnit(e:any){e.preventDefault();const f=e.currentTarget,d=new FormData(f);const r=await fetch('/api/cadastros',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:'unit',companyId:d.get('companyId'),name:d.get('name')})});if(r.ok){f.reset();setUnitCompany('');setMsg('Unidade cadastrada com sucesso.');await load()}else setMsg('Não foi possível cadastrar a unidade.')}
async function addUser(e:any){e.preventDefault();const f=e.currentTarget,d=new FormData(f);const r=await fetch('/api/usuarios',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:d.get('name'),email:d.get('email'),role:d.get('role'),companyId:d.get('companyId'),unitId:d.get('unitId')})});if(r.ok){f.reset();setUserCompany('');setMsg('Usuário cadastrado com sucesso.');await load()}else setMsg(r.status===409?'Este e-mail já está cadastrado.':'Não foi possível cadastrar o usuário.')}
async function toggleUser(x:any){const r=await fetch('/api/usuarios',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:x.id,active:!x.active,companyId:x.company_id,unitId:x.unit_id})});if(r.ok)await load()}
async function deleteUser(x:any){if(!confirm('Excluir o usuário '+x.name+'?'))return;const r=await fetch('/api/usuarios?id='+encodeURIComponent(x.id),{method:'DELETE'});if(r.ok)await load()}
return <main className="standalone adminpage"><div className="topline"><div><p>SENTINEL • ADMINISTRAÇÃO</p><h1>Administração</h1><div className="crumb">Empresas, unidades e usuários em um único local</div></div><Link className="btnlink" href="/">Dashboard</Link></div>{msg&&<div className="notice">{msg}</div>}
<section className="admincards">
<div className="panel"><div className="adminTitle"><Building2/><div><h2>Empresas</h2><p className="description">Empresas disponíveis para os registros do SENTINEL.</p></div></div><form onSubmit={addCompany} className="cadform"><label>Nome da empresa<input name="name" required placeholder="Nome da empresa"/></label><button type="submit">Cadastrar empresa</button></form><div className="cadlist">{companies.length?companies.map(x=><div key={x.id}><b>{x.name}</b><span>{units.filter(y=>y.company_id===x.id).length} unidade(s)</span></div>):<p className="description">Nenhuma empresa cadastrada.</p>}</div></div>
<div className="panel"><div className="adminTitle"><MapPin/><div><h2>Unidades</h2><p className="description">Unidades vinculadas à empresa correspondente.</p></div></div><form onSubmit={addUnit} className="cadform"><label>Empresa<select name="companyId" value={unitCompany} onChange={e=>setUnitCompany(e.target.value)} required><option value="">Selecione</option>{companies.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Nome da unidade<input name="name" required placeholder="Nome da unidade"/></label><button type="submit">Cadastrar unidade</button></form><div className="cadlist">{units.length?units.map(x=><div key={x.id}><b>{x.name}</b><span>{companies.find(c=>c.id===x.company_id)?.name||'—'}</span></div>):<p className="description">Nenhuma unidade cadastrada.</p>}</div></div>
</section>
<section className="panel adminUsers"><div className="adminTitle"><Users/><div><h2>Usuários e permissões</h2><p className="description">Cadastre o usuário, perfil e escopo organizacional.</p></div></div><form onSubmit={addUser} className="formgrid adminUserForm"><label>Nome<input name="name" required/></label><label>E-mail<input name="email" type="email" required/></label><label>Perfil<select name="role" defaultValue="CONSULTA"><option value="ADMIN">Administrador</option><option value="SSMA">SSMA</option><option value="GESTOR">Gestor</option><option value="CONSULTA">Consulta</option></select></label><label>Empresa<select name="companyId" value={userCompany} onChange={e=>setUserCompany(e.target.value)}><option value="">Todas / sem restrição</option>{companies.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Unidade<select name="unitId" disabled={!userCompany}><option value="">Todas as unidades</option>{units.filter(x=>x.company_id===userCompany).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><div className="formbutton"><button type="submit"><UserPlus/>Cadastrar usuário</button></div></form>
{users.length?<div className="tablewrap"><table><thead><tr><th>Nome</th><th>E-mail</th><th>Perfil</th><th>Empresa</th><th>Unidade</th><th>Status</th><th></th></tr></thead><tbody>{users.map(x=><tr key={x.id}><td><b>{x.name}</b></td><td>{x.email}</td><td>{x.role}</td><td>{x.company_name||'Todas'}</td><td>{x.unit_name||'Todas'}</td><td><button type="button" className={x.active?'status':'status off'} onClick={()=>toggleUser(x)}>{x.active?'Ativo':'Inativo'}</button></td><td><button type="button" className="iconDanger" onClick={()=>deleteUser(x)} title="Excluir usuário"><Trash2/></button></td></tr>)}</tbody></table></div>:<div className="empty">Nenhum usuário cadastrado.</div>}</section></main>}